global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter' # Métricas da VPS
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor' # Métricas dos Containers
    static_configs:
      - targets: ['cadvisor:8080']